version: 2

.tempates:
  .validate_template: &validate_template
    docker:
      -
        image: finalgene/hadolint:latest
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      -
        run:
          name: Validate Dockerfile
          command: |
            hadolint $VERSION/Dockerfile
  .build_template: &build_template
    docker:
      -
        image: docker:18.05.0-ce-git
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      -
        run:
          name: Build application Docker image
          command: |
            docker build --tag box-builder:$VERSION $VERSION/
      -
        run:
          name: List created images
          command: |
            docker images

jobs:
  validate-3.3:
    environment:
      VERSION: "3.3"
    <<: *validate_template
  build-3.3:
    environment:
      VERSION: "3.3"
    <<: *build_template

workflows:
  version: 2
  validate_and_build:
    jobs:
      - validate-3.3
      - build-3.3:
          requires:
            - validate-3.3
